In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Flatten

In [6]:
#  preparing in input and output data 
def prepare_data(input_series, steps):
    X, y=list(),list()
    for i in range(len(input_series)):
#         previous predict value in a input list
        prev_predict_value = steps+i
        if(prev_predict_value>len(input_series)-1):
           break
        seq_X, seq_y = input_series[i:prev_predict_value], input_series[prev_predict_value]
        X.append(seq_X)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [7]:
input_data=[10, 20, 30, 40, 50, 60, 70, 80, 90]
# no of time stamps
n_features=4
# split data
X, y = prepare_data(input_data, n_features)

In [8]:
X, y

(array([[10, 20, 30, 40],
        [20, 30, 40, 50],
        [30, 40, 50, 60],
        [40, 50, 60, 70],
        [50, 60, 70, 80]]),
 array([50, 60, 70, 80, 90]))

In [9]:
# reshaping data from 2d to 3d
features=1
print(X.shape)
X = X.reshape((X.shape[0], X.shape[1], features))

(5, 4)


# Building LSTM Model

In [11]:
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_features,features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')
model.summary()



Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 4, 50)             10400     
_________________________________________________________________
lstm_3 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 51        
Total params: 30,651
Trainable params: 30,651
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 0s - loss: 5269.2959
Epoch 2/200
1/1 - 0s - loss: 5215.9297
Epoch 3/200
1/1 - 0s - loss: 5166.9585
Epoch 4/200
1/1 - 0s - loss: 5121.3428
Epoch 5/200
1/1 - 0s - loss: 5077.6655
Epoch 6/200
1/1 - 0s - loss: 5034.2866
Epoch 7/200
1/1 - 0s - loss: 4989.4072
Epoch 8/200
1/1 - 0s - loss: 4941.3096
Epoch 9/200
1/1 - 0s - loss: 4888.6782
Epoch 10/200
1/1 - 0s - loss: 4830.5371
Epoch 11/200
1/1 - 0s - loss: 4766.1802
Epoch 12/200
1/1 - 0s - loss: 4694.9932
Epoch 13/200
1/1 - 0s - loss: 4616.3740
Epoch 14/200
1/1 - 0s - loss: 4528.8857
Epoch 15/200
1/1 - 0s - loss: 4430.1807
Epoch 16/200
1/1 - 0s - loss: 4319.1982
Epoch 17/200
1/1 - 0s - loss: 4195.8135
Epoch 18/200
1/1 - 0s - loss: 4057.5664
Epoch 19/200
1/1 - 0s - loss: 3898.6353
Epoch 20/200
1/1 - 0s - loss: 3714.7942
Epoch 21/200
1/1 - 0s - loss: 3502.1099
Epoch 22/200
1/1 - 0s - loss: 3256.5557
Epoch 23/200
1/1 - 0s - loss: 2974.3433
Epoch 24/200
1/1 - 0s - loss: 2653.3267
Epoch 25/200
1/1 - 0s - loss: 2293.8638
Epoch 26/

#  predict value

In [7]:
X_input = np.array([60, 70, 80, 90])
X_input = X_input.reshape((1, n_features, features))
yhat = model.predict(X_input, verbose=0)
yhat

array([[104.587814]], dtype=float32)

# Perdicting 10 Next Value

In [26]:
X_input = np.array([60, 70, 80, 90])
temp_input = list(X_input)
lst_out = []
i=0

while(i<10):
    if(len(temp_input)==len(X_input)):
        X_input = X_input.reshape((1, n_features, features))
        yhat = model.predict(X_input,verbose=0)
        temp_input.append(yhat[0][0])
        lst_out.append(yhat[0][0])
        lst_out.append(yhat[0][0])
        i+=1
    else:
        X_input = np.asarray(temp_input[i:])
        X_input = X_input.reshape((1, n_features,features))
        yhat = model.predict(X_input,verbose=0)
        temp_input.append(yhat[0][0])
        lst_out.append(yhat[0][0])
        i+=1
       
        
lst_out


[104.587814,
 104.587814,
 119.76469,
 136.78183,
 156.49472,
 180.84099,
 208.04935,
 239.14703,
 275.23254,
 317.35034,
 365.08643]